### ISSUE TITLE
Max Upload: 2gb

### ISSUE THREAD

**Issue by jordanbommelje** [uglyrobot/big-file-uploads#2]
Hey! I installed your plugin and Wordpress is now showing a Max Upload of 2gb instead of 50mb, but not unlimited. I checked the settings and it's set to 0 for no limit, but it's still putting a cap at 2gb. I've checked my available space and it's well above 2gb. Any thoughts? Currently running Wordpress 4.7.4. It says it's tested up to 4.5.8. Could this be a new issue?

**Comment by andtrev** [comment]
The plugin is listing the available space in the temp directory, there's no guarantee it can even upload 2gb, it's just a guesstimate of what could be uploaded. You'd have to test and see if you can successfully upload more than the 2gb it displays. There are many other factors on the server that could limit upload file size.

**Comment by jordanbommelje** [comment]
When I try to add a file larger than 2gb, it says that it's too large. What other things could I look for?

**Comment by andtrev** [comment]
You could try entering in a maximum upload size that is larger than 2gb to override the detected 2gb of free space, not sure if this will ultimately work, and you may crash the server when you try to upload a larger file than it can handle

**Comment by jordanbommelje** [comment]
When I try uploading a file larger than 2gb, I get a notification saying that it exceeds the maximum upload size of 2GB and can't try uploading it anyways.
<img width="763" alt="error" src="https://cloud.githubusercontent.com/assets/7672128/25678164/c81b74b4-3016-11e7-80c0-3640ae5f8c03.png">

Is there anything else I should be looking for on my server for for a possible reason?

**Comment by andtrev** [comment]
Right, that's because it's detecting free space of 2GB in the temp directory, you can override that number by putting in a maximum upload size instead of leaving it at zero for unlimited. Really it can't be unlimited because there's always going to be a space issue. For instance if you put in 5000 as the maximum upload size that 2GB should change to ~ 5GB, but there's no guarantee that it will allow you to upload 5GB worth of data, in some cases we've seen it truncate the upload to the space limitation, so 2GB in your case. You'd have to test and see if it works or not.
